# Generated by Django 5.0.4 on 2024-09-24 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('eliminado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='InstanciaPlayoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('puntos_por_acertar', models.IntegerField()),
                ('bono_por_resultado_exacto', models.IntegerField()),
                ('juegos_para_ganar', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.IntegerField(default=0)),
                ('equipo_campeon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.equipo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('juegos_ganados_equipo_a', models.IntegerField(blank=True, null=True)),
                ('juegos_ganados_equipo_b', models.IntegerField(blank=True, null=True)),
                ('abierta', models.BooleanField(default=False)),
                ('finalizada', models.BooleanField(default=False)),
                ('equipo_a', models.ForeignKey(limit_choices_to={'eliminado': False}, on_delete=django.db.models.deletion.CASCADE, related_name='equipo_a_series', to='polls.equipo')),
                ('equipo_b', models.ForeignKey(limit_choices_to={'eliminado': False}, on_delete=django.db.models.deletion.CASCADE, related_name='equipo_b_series', to='polls.equipo')),
                ('instancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.instanciaplayoff')),
            ],
            options={
                'unique_together': {('equipo_a', 'equipo_b')},
            },
        ),
        migrations.CreateModel(
            name='PuntosSerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.IntegerField(default=0)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.perfil')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.serie')),
            ],
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('juegos_equipo_a', models.IntegerField(default=0)),
                ('juegos_equipo_b', models.IntegerField(default=0)),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.serie')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
