# Generated by Django 5.0.4 on 2024-09-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='logo_equipo',
            field=models.URLField(null=True),
        ),
    ]
